name: Update Match Data
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install node-fetch@2

      - name: Update Match Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FTC_API_KEY: ${{ secrets.FTC_API_KEY }}
        run: node .github/scripts/update-data.js

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/match-results.json
            git commit -m "Update match results data"
            git push origin ${GITHUB_REF#refs/heads/}
          else
            echo "No changes to commit"
            q
          fi
